version: '3'
services:
  daddy:
    build: ./daddy
    ports:
      - "4567:4567"
  mommy:
    build: ./mommy
    ports:
      - "5000:5000"
  kiddopy:
    build: ./kiddo-py
    command: "pytest test_kid.py"
    depends_on:
      - daddy
      - mommy
    volumes:
      - ./kiddo-py:/code
  kiddopy-test:
    build: ./kiddo-py
    command: "pytest test_contracts.py"
    volumes:
      - ./kiddo-py:/code
  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: super_secret
      POSTGRES_DB: pact_broker
  pact-broker:
    image: dius/pact-broker
    links:
      - postgres
    ports:
      - "8087:80"
    environment:
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: super_secret
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact_broker
