version: '3'
services:
  daddy:
    build: ./daddy
    ports:
      - "4567:4567"
  mommy:
    build: ./mommy
    ports:
      - "5000:5000"
  kiddopy:
    build: ./kiddo-py
    command: "pytest test_kid.py"
    depends_on:
      - daddy
      - mommy
    volumes:
      - .:/code/kiddo-py
